config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  get 'hogehoge/hugahuga' => 'store#index'

  resources :products

  root 'store#index', as:'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>pragprog Booksオンラインストア</title>
  <%= stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%=image_tag("logo.png")%>
    <%=@page_title || "Pragmatic Bookshelf"%>
  </div>
  <div id="columns">
    <div id="side">
    <div id="cart">
      <%= render(@cart)%>
    </div>
      <ul>
        <li><a href="http://www....">ホーム</a></li>
        <li><a href="http://www..../faq">よくある質問</a></li>
        <li><a href="http://www..../news">ニュース</a></li>
        <li><a href="http://www..../contact">お問い合わせ</a></li>
        <li>現在の時刻<br><%=@time.strftime("%Y/%m/%d/%H:%M:%S") %></li>
        <% if @cart%>
        <li><%= link_to('カート', cart_path(@cart))%></li>
        <% end %>
      </ul>

      <% if session[:user_id] %>
      <ul>
      <li><%= link_to('注文',    orders_path)%></li>
       <li><%= link_to('商品',    products_path)%></li>
       <li><%= link_to('ユーザー',    users_path)%></li>
     </ul>
     <%= button_to('ログアウト', logout_path, method: :delete) %>
     <% end %>


    </div>
    <div id="main">

      <%= yield %>
  </div>
 </div>

</body>
</html>